### PR TITLE
Multiple dataset pca

### PR DESCRIPTION
**Pull request by elmer-garduno**
Implements 2-way pca.

### CODE REVIEW

**Comment by pgrosu** [comment]
Nice update @elmer-garduno, but Travis is [not happy](https://travis-ci.org/googlegenomics/spark-examples/builds/64731362) :(
```
[error] /home/travis/build/googlegenomics/spark-examples/src/main/scala/com/google/cloud/genomics/spark/examples/VariantsPca.scala:127: value _2 is not a member of org.apache.spark.rdd.RDD[com.google.cloud.genomics.spark.examples.rdd.Variant]
[error]   def getJavaData: RDD[VariantModel] = getData.map(_._2.toJavaVariant)
[error]                                                      ^
[error] /home/travis/build/googlegenomics/spark-examples/src/main/scala/com/google/cloud/genomics/spark/examples/VariantsPca.scala:127: type mismatch;
[error]  found   : List[Nothing]
[error]  required: org.apache.spark.rdd.RDD[com.google.api.services.genomics.model.Variant]
[error]   def getJavaData: RDD[VariantModel] = getData.map(_._2.toJavaVariant)
[error]                                                   ^
[error] two errors found
[error] (compile:compile) Compilation failed
[error] Total time: 148 s, completed May 30, 2015 8:02:33 PM

The command "sbt ++2.10.4 test" exited with 1.

Done. Your build exited with 1.
```

**Comment by pgrosu** [comment]
@elmer-garduno, are you running on Spark 1.3?  I'm not getting this exception every time, but at least it finishes successfully - might be a `cache()` issue:

```
Multiple main classes detected, select one to run:

 [1] com.google.cloud.genomics.spark.examples.SearchReadsExample1
 [2] com.google.cloud.genomics.spark.examples.SearchReadsExample2
 [3] com.google.cloud.genomics.spark.examples.SearchReadsExample3
 [4] com.google.cloud.genomics.spark.examples.SearchReadsExample4
 [5] com.google.cloud.genomics.spark.examples.SearchVariantsExampleKlotho
 [6] com.google.cloud.genomics.spark.examples.SearchVariantsExampleBRCA1
 [7] com.google.cloud.genomics.spark.examples.VariantsPcaDriver

Enter number: 7

[info] Running com.google.cloud.genomics.spark.examples.VariantsPcaDriver --clie                                                             nt-secrets /home/pgrosu/me/gg_client_secrets/client_secrets_java.json --spark-ma                                                             ster local[4]
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
15/05/30 19:35:59 WARN NativeCodeLoader: Unable to load native-hadoop library fo                                                             r your platform... using builtin-java classes where applicable
15/05/30 19:36:00 INFO Slf4jLogger: Slf4jLogger started
15/05/30 19:36:00 INFO Remoting: Starting remoting
15/05/30 19:36:01 INFO Remoting: Remoting started; listening on addresses :[akka                                                             .tcp://sparkDriver@eofe5.cm.cluster:33145]
Matrix size: 1095.
Running PCA on 1 datasets.
Variantset: 10473108253681171589; Refs: 17:41196311:41277499
[Stage 6:==============================================>           (8 + 2) / 10]                                                             [error] (Driver Heartbeater) java.lang.ClassNotFoundException: org.apache.spark.                                                             storage.RDDBlockId
java.lang.ClassNotFoundException: org.apache.spark.storage.RDDBlockId
        at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:340)
        at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:626)
        at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:161                                                             3)
        at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1                                                             774)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:19                                                             93)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1918)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1                                                             801)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
        at scala.collection.immutable.$colon$colon.readObject(List.scala:362)
        at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces                                                             sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:101                                                             7)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1896)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1                                                             801)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:19                                                             93)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1918)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1                                                             801)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:19                                                             93)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1918)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1                                                             801)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
        at org.apache.spark.util.Utils$.deserialize(Utils.scala:80)
        at org.apache.spark.executor.Executor$$anon$1$$anonfun$run$7$$anonfun$ap                                                             ply$6.apply(Executor.scala:415)
        at org.apache.spark.executor.Executor$$anon$1$$anonfun$run$7$$anonfun$ap                                                             ply$6.apply(Executor.scala:406)
        at scala.Option.foreach(Option.scala:236)
        at org.apache.spark.executor.Executor$$anon$1$$anonfun$run$7.apply(Execu                                                             tor.scala:406)
        at org.apache.spark.executor.Executor$$anon$1$$anonfun$run$7.apply(Execu                                                             tor.scala:404)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at org.apache.spark.executor.Executor$$anon$1.run(Executor.scala:404)
[trace] Stack trace suppressed: run last *:run for the full output.
Non zero rows in matrix: 1092 / 1095.
[Stage 14:======================>                                  (4 + 4) / 10]                                                             15/05/30 19:40:21 WARN BLAS: Failed to load implementation from: com.github.fomm                                                             il.netlib.NativeSystemBLAS
15/05/30 19:40:21 WARN BLAS: Failed to load implementation from: com.github.fomm                                                             il.netlib.NativeRefBLAS
15/05/30 19:40:23 WARN LAPACK: Failed to load implementation from: com.github.fo                                                             mmil.netlib.NativeSystemLAPACK
15/05/30 19:40:23 WARN LAPACK: Failed to load implementation from: com.github.fo                                                             mmil.netlib.NativeRefLAPACK
HG00096 10473108253681171589    0.02778657950084995     -0.006125077596608396
HG00097 10473108253681171589    -0.03359216391527189    -0.026040479900492637
HG00099 10473108253681171589    0.02847903721995417     -0.006781001863349997
HG00100 10473108253681171589    0.029577924952043005    -0.007412314295369382
HG00101 10473108253681171589    -0.03401107916688769    -0.024567344660251584
HG00102 10473108253681171589    0.0316727051981763      -0.007648174524339323
```

**Comment by elmer-garduno** [comment]
Thanks for noticing, the problem is I haven't merged with the latest changes on master which are large due to the pyspark integration. I'll do so and recreate the PR. Thanks

**Comment by pgrosu** [comment]
Ah, I see - no problem - it's a team effort :)

**Pull request closed without merging**
