### PR TITLE
Migrate to GRPC and the genomics v1 proto.

### PR DESCRIPTION
**Pull request by elmer-garduno**
This change still needs some research to make the grpc dependencies work 
on spark.

### CODE REVIEW

**Comment by elmer-garduno** [comment]
Hi @deflaux a first take on migrating to grpc, it consist basically of changing to the new utils and switching to the genomics v1 proto. 

Still I have to figure out two things, 1) make the ALPN thing work with spark, which I don't know if is required or not but it seems so. 2) Make all the grpc netty dependencies not conflict with the spark netty deps, I'll take another look later in the week.

Thanks

**Comment by deflaux** [comment]
The code changes for variants look good!  But I think this should be merged to a branch for now, not master.  It can be merged to master when gRPC is no longer behind a whitelist and reads have also been upgraded.

**Comment by elmer-garduno** [comment]
Sounds good, I'll create a branch when I got the dependency issues figured out and ready to merge.

**Comment by elmer-garduno** [comment]
Closing, will create a new PR a new branch.

**Pull request closed without merging**
